site_name: Murali Lab Wiki
site_description: Internal documentation and protocols for Murali Lab, IIT Jodhpur.
site_url: https://muralilab-ccn.github.io/lab_wiki/

repo_url: https://github.com/muralilab-ccn/lab_wiki
edit_uri: edit/main/docs/

extra_javascript:
  - javascripts/open_in_new_tab.js

theme:
  name: material
  palette:
    - primary: indigo
      accent: indigo
  features:
    - navigation.tabs        # Top horizontal navigation menu
    - navigation.top         # "Back to top" floating button
    - navigation.tracking    # Dynamic URL updates as you scroll
    - toc.follow             # Right-side table of contents follows scroll
    - search.suggest         # Live search bar as you type
    - content.code.copy      # Adds a "Copy Code" button to code blocks

nav:
  - Home: index.md
  - Lab Protocols:
      - Overview: protocols/index.md
      - EEG Acquisition Setup: protocols/EEG Recording SOP.md
      
  - Lab Meetings: meetings.md

markdown_extensions:
  - admonition
  - pymdownx.details         # Collapsible sections (??? note)
  - attr_list                # Image sizing syntax ({ width="600" })
  - md_in_html               # Custom HTML inside markdown (<figure> tags)
